name = "gearverify"
main = "src/index.ts"  # Use / not \
compatibility_date = "2026-02-09"

[assets]
directory = "."
run_worker_first = true # Important: This ensures your API isn't ignored

[[kv_namespaces]]
binding = "GEAR_VERIFY_DATA"
id = "YOUR_ACTUAL_COPIED_ID_HERE"