name = "gearverify"
main = "src/index.ts"
compatibility_date = "2026-02-09"

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "GEAR_VERIFY_DATA"
id = "c2476175d276c0c61b573349640c2325"