name = "gearverify"
main = "src/index.ts" # Change this to "index.js" if you aren't using TypeScript
compatibility_date = "2024-02-09"


[assets]
directory = "." # Change this to the folder where your index.html lives